
#define RC_I2C_ADDR 0x18

// TELEMTRIE
#define DEBUG_BAUD 115200
#define TELPORT_BAUD 19200

// VOLTAGE SENSOR
#define VOLT_SENS_PORT A1
#define VOLT_SENS_MULTIPLIKATOR 6.13

// Cureetn sensor
//#define DEBUG_SENSOR_CURRENT 
#define CUR_SENS_LEFT_PIN A3
#define CUR_SENS_RIGHT_PIN A2

// DHT11 SENSOR
//#define DHT11_PIN PE5 // Digital 3 (KILLED BY OVERVOLTAGE DOH)
//#define DEBUG_SENSOR_DHT // Debug DHT?
#define DHT11_PIN PE3 // Digital 5
#define DHT_READ_INTERVAL 500
